version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory6:
    container_name: nosqldbinmemory6
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5056:80"
    networks:
      - services-network