version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory3:
    container_name: nosqldbinmemory3
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5053:80"
    networks:
      - services-network
    depends_on:
      - memcached

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11210:11211"
    networks:
      - services-network
    command: memcached -m 64 -I 20m