version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory2:
    container_name: nosqldbinmemory2
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5052:80"
    networks:
      - services-network
    depends_on:
      - keydb

  keydb:
    container_name: keydb
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    networks:
      - services-network