version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory5:
    container_name: nosqldbinmemory5
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5055:80"
    networks:
      - services-network
    depends_on:
      - apache

  apache:
    container_name: apache
    image: apacheignite/ignite
    ports:
      - "10800:10800"
    networks:
      - services-network