version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory:
    container_name: nosqldbinmemory
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
    depends_on:
      - dragonfly

  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    networks:
      - services-network
    command: ["--conn_io_threads", "6", "--epoll_file_threads", "6", "--proactor_threads", "6"]