version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  nosqldbinmemory1:
    container_name: nosqldbinmemory1
    image: nosqldbinmemory:latest
    build:
      context: NoSqlDBInMemory
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    networks:
      - services-network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - services-network